name: Packages

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian-unstable
          - ubuntu-jammy
          - ubuntu-focal
    steps:
      - uses: actions/checkout@v4

      # Determine which PPA we should upload to
      - name: PPA
        id: ppa
        run: |
          if [[ $REF == refs/tags* ]]
          then
            echo "::set-output name=ppa::kiwixteam/release"
          else
            echo "::set-output name=ppa::kiwixteam/dev"
          fi
        env:
          REF: ${{ github.ref }}

      - uses: legoktm/gh-action-auto-dch@main
        with:
          fullname: Kiwix builder
          email: release+launchpad@kiwix.org
          distro: ${{ matrix.distro }}

      - uses: legoktm/gh-action-build-deb@debian-unstable
        if: matrix.distro == 'debian-unstable'
        name: Build package for debian-unstable
        id: build-debian-unstable
        with:
          args: --no-sign

      - uses: legoktm/gh-action-build-deb@ubuntu-jammy
        if: matrix.distro == 'ubuntu-jammy'
        name: Build package for ubuntu-jammy
        id: build-ubuntu-jammy
        with:
          args: --no-sign

      - uses: legoktm/gh-action-build-deb@ubuntu-focal
        if: matrix.distro == 'ubuntu-focal'
        name: Build package for ubuntu-focal
        id: build-ubuntu-focal
        with:
          args: --no-sign
          ppa: ${{ steps.ppa.outputs.ppa }}

      - uses: actions/upload-artifact@v3
        with:
          name: Packages for ${{ matrix.distro }}
          path: output

      - uses: legoktm/gh-action-dput@main
        name: Upload dev package
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/dev
          packages: output/*_source.changes

      - uses: legoktm/gh-action-dput@main
        name: Upload release package
        if: github.event_name == 'release' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/release
          packages: output/*_source.changes

